### ISSUE TITLE
Saving the settings in admin not working (v2.0.0)

### ISSUE THREAD

**Issue by eric2905** [rg-engineering/ioBroker.heatingcontrol#188]
js-controller 3.1.6
admin 4.2.0
Node 14.15.3

Settings can’t be saved in admin. Buttons are shown (as active = blue), but don’t have any function.
Same reported at Facebook by several users.

**Comment by rg-engineering** [comment]
ist it the same as we discuss in Forum under https://forum.iobroker.net/topic/22579/test-adapter-heatingcontrol-v2-0-x/1763

install older 1.1.x version and then update to 2.0.0. Some users reported this as a successfull workaround...

**Comment by eric2905** [comment]
> ist it the same as we discuss in Forum under https://forum.iobroker.net/topic/22579/test-adapter-heatingcontrol-v2-0-x/1763 ?

Yes, ist seems to be the same.
Tested it right now on a new/fresh installation with js-controller 3.2.4

Will later test the update over the installed v1.1.2

**Comment by rg-engineering** [comment]
I guess I have a better workaround: just configure at least one room here:
![grafik](https://user-images.githubusercontent.com/8238668/104128657-36bd9e00-5369-11eb-8736-0f417d0e0686.png)

**Comment by rg-engineering** [comment]
should be solved. don't forget to upload...

**Comment by 1337gut** [comment]
Just installed from git some minutes ago. Still can't save initial config.
Your fix should be included when installing from git, doesn't it?

**Comment by rg-engineering** [comment]
according forum not solved yet... need to analyze again...

**Comment by rg-engineering** [comment]
empty RoomList and empty DeviceList cause that error. need to be fixed...

**Comment by rg-engineering** [comment]
has anybody verified that it works now? I checked it on a complete fresh installation and it worked well. I would like to close that issue...

**Comment by 1337gut** [comment]
Works for me. Thanks!
